[en]
    title = 'Frühling demo'
    weight = 1
[ru]
    title = 'Frühling демо'
    weight = 2

[[en.menu.main]]
    name = "Travel"
    weight = 100
    identifier = "blog-travel"
    url = "/tags/travel"
[[en.menu.main]]
    name = "Work"
    weight = 200
    identifier = "blog-work"
    url = "/tags/work"
[[en.menu.main]]
    name = "Photogalleries"
    weight = 300
    identifier = "gallery"
    url = "/gallery"
[[en.menu.main]]
    name = "ru"
    identifier = "ru"
    weight = 1000
    url = "/ru"

[[ru.menu.main]]
    name = "Путешествия"
    weight = 100
    identifier = "blog-travel"
    url = "/ru/tags/путешествия/"
[[ru.menu.main]]
    name = "Работа"
    weight = 200
    identifier = "blog-work"
    url = "/ru/tags/работа/"
[[ru.menu.main]]
    name = "Фотогалереи"
    identifier = "gallery"
    weight = 300
    url = "/ru/gallery"
[[ru.menu.main]]
    name = "en"
    identifier = "en"
    weight = 1000
    url = "/"
